#!/usr/bin/env python
import sys
import _tkinter 
import Tkinter as tk

numClear =0
score=0
matrix=[['.' for x in xrange(10)] for e in xrange(22)] #global gameboard 

def main():
	root=tk.Tk()
	label=tk.Label(root, text="Tetris") #label widget
	input=tk.Entry(root) #input widget
	label.pack(side=tk.TOP) #geometry manager to put label on top of root window
	input.pack() #input is packed later so that it shows below the label
        root.bind("q", quit)
	root.bind("p", setup)
	root.bind("c", clear)
	root.mainloop() #calls to show root window

def quit(event): sys.exit(0)
	
def setup(event): printMatrix()

def clear(event):
	matrix=[['.' for x in xrange(10)] for e in xrange(22)]
	printMatrix()

def score(): print score #display score

def numClear(): print numClear #display num lines cleared

def printMatrix():
	for e in matrix: print " ".join(str(x) for x in e) 

if __name__ == "__main__":
	main()
